### ISSUE TITLE
`html_template` per document

### ISSUE THREAD

**Issue by ihodev** [revolunet/sublimetext-markdown-preview#379]
If I specify `html_template` in user settings it works like a charm, however it doesn't work when I try to override setttings in the current md-file.

```yaml
---
    settings:
        html_template: path/to/template.html
---
```
