### ISSUE TITLE
YAML Front Matter Issues

### ISSUE THREAD

**Issue by tajmone** [revolunet/sublimetext-markdown-preview#392]
After setting `"strip_yaml_front_matter": true` I've been working with MD docs containing YAML front matter and came across some issuea.

### Valueless YAML Front Matter Wan't Preview

If the YAML Front Matter is empy or contains only comments, no preview is built — ie: it doesn't even open a document in the browser. It seems that the YAML block must contain at least one variable of some sort.

I came across this issue because in my workflow I employ pre-built templates which contain YAML front matter with all values comment out, so the user can uncomment and use what is needed.

### Closing  "`...`" Not Supported

Another thing I noticed is that the YAML closing sequence "`...`" is not supported (only "`---`"). Pandoc supports both syntax, so chances are that you'll find YAML front matter ending with "`...`" instead of "`---`". From [pandoc documentation](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block):

> A YAML metadata block is a valid YAML object, delimited by a line of three hyphens (`---`) at the top and a line of three hyphens (`---`) or three dots (`...`) at the bottom.

... and the following example is provided:

``` yaml
---
title:  'This is the title: it contains a colon'
author:
- Author One
- Author Two
tags: [nothing, nothingness]
abstract: |
  This is the abstract.

  It consists of two paragraphs.
...
```
