### ISSUE TITLE
Markdown Preview 2.0 RoadMap

### ISSUE THREAD

**Issue by facelessuser** [revolunet/sublimetext-markdown-preview#393]
Roadmap is being posted here for discussion and to let people know what is *currently* being planned.

- [x] Do not vendor Python Markdown.  Python Markdown will be acquired via the current `markdown` dependency.

- [x] Python Markdown configuration changes:
    - No more defining settings as `extension(option1=a,option2=b)`.  Options will be defined as a dictionary. This is the officially recommended convention in Python Markdown. This makes internal settings handling much easier.
   - You will have to define the full extension name: `markdown.extensions.codehilite`.  We've been using a hack to maintain the old include name convention.  Now that we will use the `markdown` dependency, we won't have that hack anymore, and nor do we want to.  This will allow you to import any extension you want outside of Markdown Preview.

- [x] New line to `<br>` conversion will be dropped from GitHub emulation as GitHub no longer does this. Ref issue #374.

- [x] Originally a couple `pymdownx-extension` extensions were ported over to this plugin to give 
 a GitHub-ish feel to Markdown, these will no longer be included directly, but they will be included via dependency.  This will provide the latest versions, and also provide new extensions previously not included. Ref issue #378.

- [x] Drop ST2 so we no longer have to provide specially crafted Python Markdown versions when we try to upgrade.

- [x] Improve yaml front matter parsing: see issue #392.

- [x] Better UML JavaScript injection.  Currently we provide a script that works with flowchart.js and sequence-diagram.js, but there are scenarios where it won't work as well.  Provide updated script that injects UML at a higher level to ensure in visible elements and it gets the correct typeset, and then inject it back into the proper section.  This is similar to how others handle dynamically generated SVG content.

- [x] Link contributors in readme.

- [x] Remove "magic" Pygments configuration.  User will now explicitly configure Pygments CSS injection separately.

- [x] Require explicit parser name moving forward instead of `default`, but provide a deprecation path for the short term.

- [x] Fix GitHub header ID generation.  GitHub only lowercases ASCII chars.

- [x] Ensure default parser is Python Markdown, and enable auto-reload by default.

- [x] General refactoring and cleanup

- [x] Hopefully better documentation.

- [x] Make flake8 compatible. I'd put it up on travis for continuous integration, but I don't have that kind of control.

Possibly more

**Comment by facelessuser** [comment]
I'll elaborate why I plan on changing the settings convention for Python Markdown extensions:

1. The old way of of setting extension options via `extension(option1=a,option2=b)` only allows strings numbers, and booleans.  Arrays, dictionaries, functions are all not supported.  But, some extensions take those type of settings.

2. Keep the settings in JSON allows you to then pass in arrays and dictionaries, but functions cannot  be passed in without essentially coming up with our own notation and then adding logic to the walk the JSON structures looking for that syntax and then importing the described function.  The `pyyaml` library, which we use, already supports a notation of prefixing the function name with `!!python/name:` to pass in functions.

3. The reason me must go from an extension declaration of `codehilite` to `markdown.extensions.codehilite` is simply because Python Markdown abandoned this notation a while ago, and we had been hacking in support for the old way in our vendored Markdown.

Because of these reasons, It makes sense to just provide a setting to load Python Markdown extension settings from a YAML file.  So the plan is that Markdown Preview will get rid of the `enabled_extensions` setting, and instead have a setting called `markdown_extensions` that points to a yml file: `Packages/Markdown Preview/markdown-preview.yml`. It will contain contain like this:

```yml
markdown_extensions:
  - markdown.extensions.smart_strong
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.toc
  - markdown.extensions.meta
  - markdown.extensions.sane_lists
  - markdown.extensions.smarty
  - markdown.extensions.wikilinks
  - markdown.extensions.admonition
  - pymdownx.extrarawhtml
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      alt: short
      options:
        attributes:
            align: absmiddle
            height: 20px
            width: 20px
        image_path: https://assets-cdn.github.com/images/icons/emoji/unicode/
        non_standard_image_path: https://assets-cdn.github.com/images/icons/emoji/
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.superfences
```

To make it easy on people, it is just a list of extensions.  If you have options to set, you instead make that entry a dictionary within the list (see `pymdownx.emoji`), and add your options.  Here you can see we can configure complex settings with functions and complex structures.

**Comment by facelessuser** [comment]
Because yaml frontmatter can override settings, and the frontmatter is yaml, I think we could also allow `markdown_extensions` to not only be a string point to a yaml file, but it could be directly defined as the yaml structure.

```yml
---
    # Builtin values
    references:
        - references.md
        - abbreviations.md
        - footnotes.md

    destination: destination.html

    # Meta Data
    title: Test Page
    author:
        - John Doe
        - Jane Doe

    # Settings overrides
    settings:
        enable_uml: true
        markdown_extensions:
          - markdown.extensions.footnotes
          - markdown.extensions.attr_list
          - markdown.extensions.def_list
          - markdown.extensions.tables
          - markdown.extensions.abbr
          - markdown.extensions.toc
          - markdown.extensions.smarty
          - markdown.extensions.meta
          - markdown.extensions.wikilinks
          - markdown.extensions.admonition
          - markdown.extensions.codehilite:
              guess_lang: false
              pygments_style: github
          - pymdownx.extrarawhtml
          - pymdownx.progressbar
          - pymdownx.github
          - pymdownx.caret:
              superscript: false
---
```

Most of the work is currently done.  I'd like to evaluate some old settings and see if we can clarify them or get rid of confusing or redundant settings.   The `pymdownx` dependency is not on Package Control yet, so I need to get that up first before we could release this as well.

Current work is here: https://github.com/revolunet/sublimetext-markdown-preview/tree/dev.
